version: '3'

services:
  ### Auth Service
  mongodb_auth_service:
    container_name: mongodb_auth_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authService
      - MONGO_INITDB_ROOT_PASSWORD=authService
    volumes:
      - mongodb-authService-data:/data/db

  mongo-express-auth:
    container_name: mongo-express-auth
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://authService:authService@mongodb_auth_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=authService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=authService
    depends_on:
      - mongodb_auth_service
    ports:
      - "8081:8081"

  auth-service:
    build: ./ride-off-smart-ride-app-auth-service
    depends_on:
      - mongodb_auth_service
    deploy:
      mode: replicated
      replicas: 1

  ### Verification Service
  mongodb_verification_service:
    container_name: mongodb_verification_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=verificationService
      - MONGO_INITDB_ROOT_PASSWORD=verificationService
    volumes:
      - mongodb-verificationService-data:/data/db

  mongo-express-verification:
    container_name: mongo-express-verification
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://verificationService:verificationService@mongodb_verification_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=verificationService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=verificationService
    depends_on:
      - mongodb_verification_service
    ports:
      - "8082:8081"# 8082 = host port, 8081 = container port

  verification-service:
    build: ./ride-off-smart-ride-app-verification-service
    depends_on:
      - mongodb_verification_service
    deploy:
      mode: replicated
      replicas: 1
#    ports: TODO expose if dev tools are needed
#      - "8001:8000"  # For nestjs dev tools

  ### Admin Service
  mongodb_admin_service:
    container_name: mongodb_admin_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminService
      - MONGO_INITDB_ROOT_PASSWORD=adminService
    volumes:
      - mongodb-adminService-data:/data/db


  mongo-express-admin:
    container_name: mongo-express-admin
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://adminService:adminService@mongodb_admin_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=adminService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=adminService
    depends_on:
      - mongodb_admin_service
    ports:
      - "8083:8081"

  admin-service:
    build: ./ride-off-smart-ride-app-admin-service
    depends_on:
      - mongodb_admin_service
    deploy:
      mode: replicated
      replicas: 1

  ### Ride Service
  mongodb_ride_service:
    container_name: mongodb_ride_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rideService
      - MONGO_INITDB_ROOT_PASSWORD=rideService
    volumes:
      - mongodb-rideService-data:/data/db

  mongo-express-ride:
    container_name: mongo-express-ride
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://rideService:rideService@mongodb_ride_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=rideService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=rideService
    depends_on:
      - mongodb_ride_service
    ports:
      - "8084:8081"

  ride-service:
    build: ./ride-off-smart-ride-app-ride-service
    depends_on:
      - mongodb_ride_service
    deploy:
      mode: replicated
      replicas: 1

  ### Reverse Proxy - Nginx
  nginx:
    container_name: nginx
    build: ./ride-off-smart-ride-app-nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - verification-service
      - admin-service
      - ride-service


volumes:
  mongodb-authService-data:
    driver: local

  mongodb-verificationService-data:
    driver: local

  mongodb-adminService-data:
    driver: local

  mongodb-rideService-data:
    driver: local